services:
  libretranslate:
    image: libretranslate/libretranslate
    ports: 
      - "5000:5000"
    restart: unless-stopped
    command: ["--load-only", "en,ru"]
    deploy:
      resources:
        limits:
          memory: 2G
